[versions]
agp = "8.13.0"
androidSdk = "11.13.1"
converterGson = "3.0.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
lombok = "1.18.40"
material = "1.10.0"
constraintlayout = "2.1.4"
materialVersion = "1.13.0"
navigationFragment = "2.6.0"
navigationUi = "2.6.0"
playServicesMaps = "19.2.0"
recyclerview = "1.3.1"
retrofit = "3.0.0"
roomCommonJvm = "2.8.0"
roomRuntimeJvm = "2.8.0"
playServicesLocation = "21.3.0"

[libraries]
android-sdk = { module = "org.maplibre.gl:android-sdk", version.ref = "androidSdk" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v1130 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
room-common-jvm = { group = "androidx.room", name = "room-common-jvm", version.ref = "roomCommonJvm" }
room-runtime-jvm = { group = "androidx.room", name = "room-runtime-jvm", version.ref = "roomRuntimeJvm" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

